# -*- coding: utf-8 -*-
"""Exploratory-data-analysis---sport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101Ncy0jp1B3sLsW1n9Be3Pxb5CzTEUgS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10,5)

# Load dataset
ipl = pd.read_csv("/content/matches.csv")

# View first 5 rows
ipl.head()

"""# Dataset shape  Column information # Check missing values

"""

ipl.shape


ipl.info()


ipl.isnull().sum()

"""# Countings wins per team

---# Display top 10 teams




---



---


"""

team_wins = ipl['winner'].value_counts()


team_wins.head(10)

team_wins.head(10).plot(kind='bar', color='orange')
plt.title("Most Successful IPL Teams")
plt.xlabel("Team")
plt.ylabel("Number of Wins")
plt.show()

# Teams winning toss AND match
toss_win_match_win = ipl[ipl['toss_winner'] == ipl['winner']]

# Percentage calculation
percentage = (len(toss_win_match_win) / len(ipl)) * 100
percentage

"""# Matches won batting first

# Matches won while chasing

# Pie chart
"""

bat_first = ipl[ipl['win_by_runs'] > 0].shape[0]


chasing = ipl[ipl['win_by_wickets'] > 0].shape[0]


plt.pie([bat_first, chasing], labels=['Batting First', 'Chasing'],
        autopct='%1.1f%%', startangle=140)
plt.title("Win Distribution: Batting First vs Chasing")
plt.show()

"""**Count player of match awards**"""

top_players = ipl['player_of_match'].value_counts().head(10)

top_players

top_players.plot(kind='bar', color='green')
plt.title("Top Performing Players (Player of the Match)")
plt.xlabel("Player")
plt.ylabel("Awards")
plt.show()

venue_wins = ipl['venue'].value_counts().head(10)

venue_wins

venue_wins.plot(kind='bar', color='purple')
plt.title("Matches Played at Top Venues")
plt.xlabel("Venue")
plt.ylabel("Matches")
plt.show()

print("Recommended Teams for Endorsements:")
print(team_wins.head(5))

print("\nRecommended Players for Endorsements:")
print(top_players.head(5))